### ISSUE TITLE
Updating index fails

### ISSUE THREAD

**Issue by donat1** [til-schneider/regain#3]
Hi

We use regain since years and we find, that it's one of the best index crawler.

Now, I have unfortunately an error, so I can't use the product anymore (Client-Version). It ends by indexing with following:
... Finished crawling
Updating index failed

What could that be?

Kind regards
don

**Comment by til-schneider** [comment]
Please follow instructions of the manual page [How to find the error cause](http://regain.murfman.de/config:howto_find_error_cause).

**Comment by donat1** [comment]
Hi Til


Thanks for your hint. I could solve the problem. It was a permission
conflict. I then set the whole directory to read and write to
everybody. Now, it works again.


Kind regards

Donat Waber


Am Dienstag, den 28.04.2020 um 16:07 schrieb Til Schneider:








Please follow instructions of the manual page How to find the error
cause [1].



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].





Links:
------
[1] http://regain.murfman.de/config:howto_find_error_cause
[2]
https://github.com/til-schneider/regain/issues/3#issuecomment-620630036
[3]
