### ISSUE TITLE
Tomcat shows 403 error when open files on result page

### ISSUE THREAD

**Issue by ed29** [til-schneider/regain#8]
Hi:

My  installation version is regain server 2.1.0,and tomcat7,system is archlinux.
The problem is: The result files can't be opened by blowser,it shows 403,says The server understood the request but refuses to authorize it.

![图片](https://user-images.githubusercontent.com/3096827/134799429-ecb47b28-73d3-465f-bab3-c4e6a46dc653.png)
403 error
![图片](https://user-images.githubusercontent.com/3096827/134799559-0fbb86da-a892-4a1c-a477-1c3a1a2f4a4d.png)
result files

**Comment by til-schneider** [comment]
By default, regain only grants file access for requests from localhost. regain has no user rights management on its own. But you can hook-in your own user management (or single-sign-on).

See manual: http://regain.murfman.de/features:access_rights_management
